// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeScreenTimeout():Promise<string>;

export function DisableCmd():Promise<string>;

export function DisableDownloads():Promise<string>;

export function DisableFacebook():Promise<string>;

export function DisableWindowsUpdates():Promise<string>;
