// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeScreenTimeout() {
  return window['go']['main']['App']['ChangeScreenTimeout']();
}

export function DisableCmd() {
  return window['go']['main']['App']['DisableCmd']();
}

export function DisableDownloads() {
  return window['go']['main']['App']['DisableDownloads']();
}

export function DisableFacebook() {
  return window['go']['main']['App']['DisableFacebook']();
}

export function DisableWindowsUpdates() {
  return window['go']['main']['App']['DisableWindowsUpdates']();
}
